name: dijon-lab

include:
  - authentik/docker-compose.yml
  - immich/docker-compose.yml
  - cloudflared/docker-compose.yml
  - traefik/docker-compose.yml

# Shared network so all included services can reach each other
networks:
  default:
    name: lab
    driver: bridge
